title = "CryptUtil"
gitRepoUrl = "https://github.com/encrxpt3d/CryptUtil"

gitSourceBranch = "main"
changelog = false

[docusaurus]
onBrokenLinks = "throw"
onBrokenMarkdownLinks = "warn"

# From git:
organizationName = "encrxpt3d"
projectName = "CryptUtil"
url = "https://encrxpt3d.github.io"
baseUrl = "/CryptUtil"
tagline = "A collection of utility modules for Roblox"

[home]
enabled = true
includeReadme = false

classOrder = [
    "api"
]