title = "MyProjectName"  # From Git
gitRepoUrl = "https://github.com/evaera/moonwave" # From Git

gitSourceBranch = "main"
changelog = true
classOrder = []

[docusaurus]
onBrokenLinks = "throw"
onBrokenMarkdownLinks = "warn"
favicon = ""
tagline = "A collection of utility modules for Roblox"

# From git:
organizationName = "AuthorName"
projectName = "MyProjectName"
url = "https://AuthorName.github.io"
baseUrl = "/MyProjectName"
tagline = "Your project's tagline"

[home]
enabled = true
includeReadme = false